repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
    - id: black
      language_version: python3

  - repo: https://github.com/keewis/blackdoc
    rev: v0.3.9
    hooks:
    - id: blackdoc
      additional_dependencies: ["black[jupyter]"]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
    - id: codespell
      types_or: [python, markdown]
      additional_dependencies: [tomli]
